In [23]:
import pandas as pd
import geopandas as gpd
import folium

In [24]:
lat = -5.5111966
long =122.871147

In [25]:
m = folium.Map(
    location=[lat, long],
    zoom_start=16
)

In [26]:
folium.Marker(
    location=[-5.511966, 482.871147],
    tooltip="Lokasi Wahyu"
).add_to(m)

In [27]:
folium.Marker(
    location=[-5.512300, 122.872000],
    tooltip="Lokasi Zaliyanti"
).add_to(m)

In [28]:
folium.Polygon(
    locations=[
        [-5.511966, 122.871147],
        [-5.511700, 122.871700],
        [-5.512300, 122.872000],
        [-5.512600, 122.871300]
    ],
    color="red",
    fill=True,
    fill_color="red",
    fill_opacity=0.4,
    tooltip="Area Rumah Mutiyah"
).add_to(m)

In [29]:
folium.PolyLine(
    locations=[
        [-5.511966, 122.871147],
        [-5.511850, 122.871220],
        [-5.511720, 122.871350],
        [-5.511600, 122.871500],
        [-5.511480, 122.871650],
        [-5.511350, 122.871800]
    ],
    color="blue",
    weight=5,
    tooltip="Jalan Poros"
).add_to(m)

In [30]:
m.save('map.html')

In [31]:
df = pd.read_excel("dataa.xlsx")
df

           nama  latitude  longtitude
0  Lokasi Wahyu -5.511966  122.871147
1       Titik 2 -5.512500  122.872000

In [32]:
gdf = gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(df.longtitude, df.latitude),
    crs="EPSG:4326"
)
gdf

           nama  latitude  longtitude                    geometry
0  Lokasi Wahyu -5.511966  122.871147  POINT (122.87115 -5.51197)
1       Titik 2 -5.512500  122.872000     POINT (122.872 -5.5125)

In [33]:
folium.GeoJson(gdf).add_to(m)